# Generated by Django 5.2.3 on 2025-06-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('assistant_id', models.AutoField(primary_key=True, serialize=False)),
                ('assistant_sms', models.TextField()),
            ],
            options={
                'db_table': 'assistant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('breed_id', models.AutoField(primary_key=True, serialize=False)),
                ('breed_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'breed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('size', models.IntegerField(blank=True, null=True)),
                ('uploadedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'file',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Knowledges',
            fields=[
                ('knowledges_id', models.AutoField(primary_key=True, serialize=False)),
                ('knowledges', models.TextField()),
            ],
            options={
                'db_table': 'knowledges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medrecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('clinicorvet', models.CharField(blank=True, max_length=50, null=True)),
                ('dosage', models.CharField(blank=True, max_length=30, null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medrecord',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('pets_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('imageurl', models.CharField(blank=True, max_length=255, null=True)),
                ('specialnotes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Petsprofile',
            fields=[
                ('animals_id', models.AutoField(primary_key=True, serialize=False)),
                ('breedcharacteristics', models.TextField(blank=True, null=True)),
                ('commonname', models.CharField(blank=True, max_length=50, null=True)),
                ('scientificname', models.CharField(blank=True, max_length=50, null=True)),
                ('taxonomyclass', models.CharField(blank=True, max_length=50, null=True)),
                ('conservationstatus', models.CharField(blank=True, max_length=50, null=True)),
                ('habitat', models.CharField(blank=True, max_length=50, null=True)),
                ('diet', models.CharField(blank=True, max_length=50, null=True)),
                ('averagelifespan', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('colour', models.CharField(blank=True, max_length=10, null=True)),
                ('behavior', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'petsprofile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('imageurl', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shopproduct',
            fields=[
                ('pk', models.CompositePrimaryKey('shop_id', 'product_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'shopproduct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('species_id', models.AutoField(primary_key=True, serialize=False)),
                ('species_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'species',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userassistant',
            fields=[
                ('pk', models.CompositePrimaryKey('user_id', 'assistant_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'userassistant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userknowledges',
            fields=[
                ('pk', models.CompositePrimaryKey('user_id', 'knowledges_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'userknowledges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('preferredlanguage', models.CharField(blank=True, max_length=20, null=True)),
                ('clinic', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('specialization', models.CharField(blank=True, max_length=50, null=True)),
                ('experience', models.CharField(blank=True, max_length=50, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('nameoforganization', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user_profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
