# Generated by Django 5.2.3 on 2025-06-24 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0001_initial'),
    ]

    operations = [
    ]
